version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: channel_manager_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: channel_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: channel_manager_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
